# Generated by Django 5.1.3 on 2024-12-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parents',
            new_name='parent',
        ),
    ]
