# Generated by Django 5.1.3 on 2024-12-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Karama',
            new_name='Karma',
        ),
    ]
