# Generated by Django 5.1.3 on 2024-12-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_karama_userprofile_karma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Karma',
            new_name='karma',
        ),
    ]
